import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Loader2, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/share/$shareId")({
  head: () => ({
    meta: [
      { title: "Play — PlayIQ" },
      { name: "description", content: "AI coaching breakdown of a single possession." },
    ],
  }),
  component: SharePage,
});

type Play = {
  id: string; possession_index: number; start_seconds: number; end_seconds: number;
  outcome: string; what_happened: string; what_went_right: string | null;
  what_went_wrong: string | null; alternative: string | null;
  confidence: "low" | "medium" | "high"; share_id: string;
};

function SharePage() {
  const { shareId } = Route.useParams();

  const { data, isLoading } = useQuery({
    queryKey: ["share", shareId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("plays")
        .select("id,possession_index,start_seconds,end_seconds,outcome,what_happened,what_went_right,what_went_wrong,alternative,confidence,share_id")
        .eq("share_id", shareId)
        .maybeSingle();
      if (error) throw error;
      return data as Play | null;
    },
  });

  if (isLoading) {
    return <div className="grid min-h-screen place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  }
  if (!data) {
    return (
      <div className="grid min-h-screen place-items-center px-4 text-center">
        <div>
          <h1 className="text-2xl font-semibold">Play not found</h1>
          <p className="mt-2 text-sm text-muted-foreground">This share link is invalid or was removed.</p>
          <Link to="/" className="mt-4 inline-block text-primary underline">Home</Link>
        </div>
      </div>
    );
  }

  const p = data;
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/60">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="grid h-7 w-7 place-items-center rounded-md bg-primary text-primary-foreground font-bold text-sm">P</div>
            <span className="font-semibold">PlayIQ</span>
          </Link>
          <span className="text-xs text-muted-foreground">Shared play card</span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-10">
        <div className="text-xs uppercase tracking-[0.3em] text-primary">Possession #{p.possession_index}</div>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">{p.what_happened}</h1>

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <Badge variant="secondary">{p.outcome.replace("_", " ")}</Badge>
          <Badge variant="outline">Confidence: {p.confidence}</Badge>
          <span className="scoreboard text-xs text-muted-foreground">
            {fmt(p.start_seconds)}–{fmt(p.end_seconds)}
          </span>
        </div>

        <div className="mt-8 space-y-5">
          {p.what_went_right && <Row label="What went right" body={p.what_went_right} tone="good" />}
          {p.what_went_wrong && <Row label="What went wrong" body={p.what_went_wrong} tone="bad" />}
          {p.alternative && <Row label="Do differently" body={p.alternative} tone="warn" />}
        </div>

        <div className="mt-10 flex items-center gap-2 rounded-lg border border-border bg-card/60 p-4 text-xs text-muted-foreground">
          <Sparkles className="h-4 w-4 text-primary" />
          Generated by PlayIQ AI film analysis.
        </div>
      </main>
    </div>
  );
}

function Row({ label, body, tone }: { label: string; body: string; tone: "good" | "bad" | "warn" }) {
  const color = tone === "good" ? "text-[color:var(--good)]" : tone === "bad" ? "text-[color:var(--bad)]" : "text-[color:var(--warn)]";
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-[0.25em] ${color}`}>{label}</div>
      <p className="mt-1 leading-relaxed">{body}</p>
    </div>
  );
}

function fmt(sec: number) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}
